apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - image: {{ .Values.container.image }}:{{ .Values.container.tagVersion }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: 'VAULT_ENABLED'
              value: {{ .Values.env.vault_enabled | quote }}
            - name: 'PROXY_INJECTOR_ENABLED'
              value: {{ .Values.env.proxy_injector_enabled | quote }}
            - name: 'VAULT_SVC_NAME'
              value: {{ .Values.env.vault_svc_name | quote }}
            - name: 'PROXY_INJ_SVC_NAME'
              value: {{ .Values.env.proxy_inj_svc_name | quote }}
            - name: 'VAULT_NS'
              value: {{ .Values.env.vault_ns | quote }}
            - name: 'PROXY_INJ_NS'
              value: {{ .Values.env.proxy_inj_ns | quote }}
          name: {{ .Values.appName }}
          ports:
            - containerPort: 8080
