apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-svc
  namespace: test-app-ns
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
